name: campus_vibe
description: A social platform for university students across Pakistan

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_analytics: ^10.7.4
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  timeago: ^3.5.0
  uuid: ^3.0.7
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  connectivity_plus: ^4.0.2
  rxdart: ^0.27.7
  # Remove problematic packages
  # pull_to_refresh: ^2.0.0
  local_auth: ^2.1.8
  # Add new dependencies
  firebase_auth_web: ^5.8.12
  js: ^0.6.7
  refresh_indicator: ^0.2.1
  # Add missing models package
  collection: ^1.17.2
  firebase_crashlytics: ^3.4.0
  device_info_plus: ^9.0.0
  flutter_local_notifications: ^16.1.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
